automerge: true
files:
  changelogs/: {}
  changelogs/fragments/:
    support: community
  $modules/database/saphana/hana_query.py:
    maintainers: rainerleber
  $modules/files/sapcar_extract.py:
    maintainers: rainerleber
  $modules/system/sap_task_list_execute:
    maintainers: rainerleber
#########################
  tests/:
    labels: tests
  tests/unit/:
    labels: unit
    support: community
  tests/integration:
    labels: integration
    support: community
macros:
  modules: plugins/modules